version: '3.2'
services:
  app:
    build:
      context: .
      args: {}
    command: uwsgi-production
    depends_on:
    - postgres
    volumes:
    - data:/opt/ngw/data
    ports:
    - 8080:8080
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: ngw
volumes:
  data: {}
