version: '3.2'
services:
  app:
    build:
      context: .
      args:
        uid: 1000
        gid: 1000
    command: pserve-development
    depends_on:
    - postgres
    volumes:
    - data:/opt/ngw/data
    - ./package:/opt/ngw/package
    ports:
    - 8080:8080
  postgres:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: ngw
volumes:
  data: {}
